/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.egcc.app.view;

import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo Coronel
 */
public class DemoRadioButton extends javax.swing.JFrame {

  /**
   * Creates new form DemoRadioButton
   */
  public DemoRadioButton() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    bgGaseosa = new javax.swing.ButtonGroup();
    bgAcompania = new javax.swing.ButtonGroup();
    jLabel1 = new javax.swing.JLabel();
    rbCocaCola = new javax.swing.JRadioButton();
    rbInkaCola = new javax.swing.JRadioButton();
    rbGuarana = new javax.swing.JRadioButton();
    jLabel2 = new javax.swing.JLabel();
    rbGalleta = new javax.swing.JRadioButton();
    rbKeke = new javax.swing.JRadioButton();
    rbTorta = new javax.swing.JRadioButton();
    btnVer = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setText("Gaseosa");

    bgGaseosa.add(rbCocaCola);
    rbCocaCola.setText("Coca Cola");
    rbCocaCola.setActionCommand("COCA COLA");

    bgGaseosa.add(rbInkaCola);
    rbInkaCola.setText("Inka Cola");
    rbInkaCola.setActionCommand("INKA COLA");

    bgGaseosa.add(rbGuarana);
    rbGuarana.setText("Guarana");
    rbGuarana.setActionCommand("GUARANA");

    jLabel2.setText("Acompañamiento");

    bgAcompania.add(rbGalleta);
    rbGalleta.setText("Galleta");
    rbGalleta.setActionCommand("GALLETA");

    bgAcompania.add(rbKeke);
    rbKeke.setText("Keke");
    rbKeke.setActionCommand("KEKE");

    bgAcompania.add(rbTorta);
    rbTorta.setText("Torta");
    rbTorta.setActionCommand("TORTA");

    btnVer.setText("Ver");
    btnVer.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnVerActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(40, 40, 40)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(rbCocaCola)
              .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(rbInkaCola)
              .addComponent(rbGuarana))
            .addGap(67, 67, 67)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(rbGalleta)
              .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(rbKeke)
              .addComponent(rbTorta)))
          .addGroup(layout.createSequentialGroup()
            .addGap(93, 93, 93)
            .addComponent(btnVer, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(64, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(34, 34, 34)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addGap(18, 18, 18)
            .addComponent(rbCocaCola)
            .addGap(18, 18, 18)
            .addComponent(rbInkaCola)
            .addGap(18, 18, 18)
            .addComponent(rbGuarana))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel2)
            .addGap(18, 18, 18)
            .addComponent(rbGalleta)
            .addGap(18, 18, 18)
            .addComponent(rbKeke)
            .addGap(18, 18, 18)
            .addComponent(rbTorta)))
        .addGap(36, 36, 36)
        .addComponent(btnVer, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(49, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
    // Datos
    String gaseosa = bgGaseosa.getSelection().getActionCommand();
    String acompania = bgAcompania.getSelection().getActionCommand();
    // Reporte
    String repo = gaseosa + " - " + acompania;
    JOptionPane.showMessageDialog(rootPane, repo);
  }//GEN-LAST:event_btnVerActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(DemoRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(DemoRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(DemoRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(DemoRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new DemoRadioButton().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup bgAcompania;
  private javax.swing.ButtonGroup bgGaseosa;
  private javax.swing.JButton btnVer;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JRadioButton rbCocaCola;
  private javax.swing.JRadioButton rbGalleta;
  private javax.swing.JRadioButton rbGuarana;
  private javax.swing.JRadioButton rbInkaCola;
  private javax.swing.JRadioButton rbKeke;
  private javax.swing.JRadioButton rbTorta;
  // End of variables declaration//GEN-END:variables
}
